# hosts/desktop/hardware-configuration.nix - Example hardware configuration
#
# This is a template hardware configuration. On a real system, this file would be
# generated by nixos-generate-config and would contain your actual hardware details.
#
# To generate a real hardware configuration:
#   sudo nixos-generate-config --root /

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Example boot configuration
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];  # or "kvm-amd" for AMD CPUs
  boot.extraModulePackages = [ ];

  # Example filesystem configuration
  # Replace these with your actual partitions
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/xxxx-xxxx";
    fsType = "vfat";
  };

  # Swap configuration
  swapDevices = [ ];

  # CPU and system configuration
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
