# hosts/fractal/default.nix - Fractal machine configuration
{
  config,
  lib,
  pkgs,
  sops-secrets,
  ...
}:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Import modules from this flake
    ../../modules/common/base.nix
    ../../modules/common/niri.nix
    ../../modules/features/development.nix
    ../../modules/features/virtualization.nix
    ../../modules/features/zfs.nix
    ../../modules/features/immich.nix
    ../../modules/features/notes.nix
  ];

  # Hostname
  networking.hostName = "fractal";
  networking.hostId = "ef78e08d"; # Required by ZFS; derived from /etc/machine-id

  # Override systemd-boot from base.nix with GRUB for dual-boot support
  boot.loader.systemd-boot.enable = lib.mkForce false;
  boot.loader.timeout = 10;
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    device = "nodev";
    extraConfig = "set timeout_style=menu";
    extraEntries = ''
      menuentry "Windows" {
        insmod part_gpt
        insmod fat
        insmod chain
        search --no-floppy --fs-uuid --set=root 0F1E-B6C7
        chainloader /EFI/Microsoft/Boot/bootmgfw.efi
      }
      menuentry "Ubuntu" {
        insmod part_gpt
        insmod fat
        insmod chain
        search --no-floppy --fs-uuid --set=root 0F1E-B6C7
        chainloader /EFI/ubuntu/shimx64.efi
      }
    '';
  };
  boot.loader.efi.efiSysMountPoint = "/boot/efi";

  # Nvidia GPU
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    open = false; # Proprietary module - more stable for rendering
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
    powerManagement.enable = true; # Fix GPU state restore after suspend/resume
  };

  # sops-nix configuration - age key derived from SSH host key
  sops.age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
  sops.defaultSopsFile = "${sops-secrets}/secrets/common.yaml";
  sops.secrets.github_ssh_key = {
    owner = "mallain";
    mode = "0600";
  };
  # Enable development features
  mySystem.development = {
    enable = true;
    languages = {
      python = true;
      rust = true;
      nodejs = true;
      go = true;
    };
  };

  # Enable ZFS
  mySystem.zfs.enable = true;

  # Enable Immich
  mySystem.immich.enable = true;

  # Enable notes server
  mySystem.notes.enable = true;

  # Enable Docker
  mySystem.virtualization = {
    enable = true;
    backend = "docker";
  };

  # Removable storage auto-mounting
  services.udisks2.enable = true;
  services.gvfs.enable = true;

  # Fonts
  fonts.packages = with pkgs; [
    nerd-fonts.meslo-lg
  ];

  # Additional packages
  programs.firefox.enable = true;
  environment.systemPackages = with pkgs; [
    google-chrome
    alacritty
    sublime-merge
    sops
    ssh-to-age
  ];
}
