# hosts/fractal/default.nix - Fractal machine configuration
{
  config,
  lib,
  pkgs,
  sops-secrets,
  ...
}:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Import modules from this flake
    ../../modules/common/base.nix
    ../../modules/common/niri.nix
    ../../modules/features/development.nix
    ../../modules/features/virtualization.nix
    ../../modules/features/zfs.nix
    ../../modules/features/immich.nix
    ../../modules/features/notes.nix
    ../../modules/features/llm-agent.nix
    ../../modules/features/health-check.nix
    ../../modules/features/signal-cli.nix
    ../../modules/features/local-dns.nix
  ];

  # Hostname
  networking.hostName = "fractal";
  networking.hostId = "ef78e08d"; # Required by ZFS; derived from /etc/machine-id

  # Override systemd-boot from base.nix with GRUB for dual-boot support
  boot.loader.systemd-boot.enable = lib.mkForce false;
  boot.loader.timeout = 10;
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    device = "nodev";
    extraConfig = "set timeout_style=menu";
    extraEntries = ''
      menuentry "Windows" {
        insmod part_gpt
        insmod fat
        insmod chain
        search --no-floppy --fs-uuid --set=root 0F1E-B6C7
        chainloader /EFI/Microsoft/Boot/bootmgfw.efi
      }
      menuentry "Ubuntu" {
        insmod part_gpt
        insmod fat
        insmod chain
        search --no-floppy --fs-uuid --set=root 0F1E-B6C7
        chainloader /EFI/ubuntu/shimx64.efi
      }
    '';
  };
  boot.loader.efi.efiSysMountPoint = "/boot/efi";

  # Nvidia GPU
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    open = false; # Proprietary module - more stable for rendering
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
    powerManagement.enable = true; # Fix GPU state restore after suspend/resume
  };

  # sops-nix configuration - age key derived from SSH host key
  sops.age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
  sops.defaultSopsFile = "${sops-secrets}/secrets/common.yaml";
  sops.secrets.github_ssh_key = {
    owner = "mallain";
    mode = "0600";
  };
  sops.secrets.hermes_openrouter_key = { };
  sops.secrets.hermes_exa_key = { };
  sops.secrets.hermes_signal_account = {
    owner = "signal-cli";
  };
  # Write an actual file (not a sops symlink) so virtiofs can expose it inside the VM
  system.activationScripts.hermes-agent-secrets = {
    deps = [ "setupSecrets" ];
    text = ''
      mkdir -p /var/lib/microvms/hermes/agent-secrets
      {
        printf 'OPENROUTER_API_KEY=%s\n' "$(cat ${config.sops.secrets.hermes_openrouter_key.path})"
        printf 'EXA_API_KEY=%s\n' "$(cat ${config.sops.secrets.hermes_exa_key.path})"
        printf 'SIGNAL_HTTP_URL=http://10.0.0.1:8081\n'
        printf 'SIGNAL_ACCOUNT=%s\n' "$(cat ${config.sops.secrets.hermes_signal_account.path})"
        printf 'SIGNAL_ALLOWED_USERS=%s\n' "$(cat ${config.sops.secrets.hermes_signal_account.path})"
        printf 'SIGNAL_HOME_CHANNEL=%s\n' "$(cat ${config.sops.secrets.hermes_signal_account.path})"
      } > /var/lib/microvms/hermes/agent-secrets/env
      chmod 0444 /var/lib/microvms/hermes/agent-secrets/env
    '';
  };

  mySystem.signalCli = {
    enable = true;
    accountFile = config.sops.secrets.hermes_signal_account.path;
  };
  # Enable development features
  mySystem.development = {
    enable = true;
    languages = {
      python = true;
      rust = true;
      nodejs = true;
      go = true;
    };
  };

  # Enable ZFS
  mySystem.zfs.enable = true;

  # Enable Immich
  mySystem.immich.enable = true;

  # Enable notes server
  mySystem.notes.enable = true;

  # Health check timer with Signal notification on failure
  mySystem.healthCheck = {
    enable = true;
    notify = {
      enable = true;
      accountFile = config.sops.secrets.hermes_signal_account.path;
    };
  };

  mySystem.localDns = {
    enable = true;
    listenAddress = "192.168.50.154";
    hosts = {
      "fractal.mitchellallain.com" = "192.168.50.154";
      "immich.mitchellallain.com" = "192.168.50.154";
      "notes.mitchellallain.com" = "192.168.50.154";
      "dashboard.mitchellallain.com" = "192.168.50.154";
    };
  };

  services.nginx.virtualHosts."dashboard.mitchellallain.com" = {
    locations."/" = {
      proxyPass = "http://127.0.0.1:${toString config.mySystem.dashboard.port}";
      proxyWebsockets = true;
    };
  };

  mySystem.immich.hostname = "immich.mitchellallain.com";
  mySystem.notes.hostname = "notes.mitchellallain.com";

  mySystem.llmAgent.enable = false;

  # Enable Docker
  mySystem.virtualization = {
    enable = true;
    backend = "docker";
  };

  # Suppress failure when a printer is powered off at rebuild time
  systemd.services.ensure-printers.serviceConfig.SuccessExitStatus = [
    0
    1
  ];

  # Printers
  services.printing.drivers = [ pkgs.brlaser ];
  hardware.printers = {
    ensureDefaultPrinter = "Brother_HL-L2360DW";
    ensurePrinters = [
      {
        name = "Brother_HL-L2360DW";
        location = "Home";
        deviceUri = "socket://192.168.50.241";
        model = "drv:///brlaser.drv/brl2360d.ppd";
        ppdOptions.PageSize = "Letter";
      }
      {
        name = "Epson_ET-2800";
        location = "Home";
        deviceUri = "ipp://192.168.50.159/ipp/print";
        model = "everywhere";
        ppdOptions.PageSize = "Letter";
      }
    ];
  };

  # Removable storage auto-mounting
  services.udisks2.enable = true;
  services.gvfs.enable = true;

  # Fonts
  fonts.packages = with pkgs; [
    nerd-fonts.meslo-lg
  ];

  # Additional packages
  programs.firefox.enable = true;
  environment.systemPackages = with pkgs; [
    google-chrome
    alacritty
    sublime-merge
    sops
    ssh-to-age
    nvtopPackages.nvidia
  ];
}
